title:My fisrt Github page
Date: 2018-10-28
author: Bater Kari
email: bkari@optimum.net
description: > # this means to ignore newlines until "baseurl:"
 This my very first blog on my very first GitHub page.

# social links
twitter_username: your-twitter-handle
github_username:  @BaterKari

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
